// Code generated by counterfeiter. DO NOT EDIT.
package providerfakes

import (
	"context"
	"sync"

	"github.com/tobyrushton/flyvia/packages/search/itinery"
	"github.com/tobyrushton/flyvia/packages/search/provider"
)

type FakeProvider struct {
	ExploreStub        func(context.Context, provider.Request, string) ([]itinery.ExploreItinery, error)
	exploreMutex       sync.RWMutex
	exploreArgsForCall []struct {
		arg1 context.Context
		arg2 provider.Request
		arg3 string
	}
	exploreReturns struct {
		result1 []itinery.ExploreItinery
		result2 error
	}
	exploreReturnsOnCall map[int]struct {
		result1 []itinery.ExploreItinery
		result2 error
	}
	SearchStub        func(context.Context, provider.Request) ([]itinery.Itinery, error)
	searchMutex       sync.RWMutex
	searchArgsForCall []struct {
		arg1 context.Context
		arg2 provider.Request
	}
	searchReturns struct {
		result1 []itinery.Itinery
		result2 error
	}
	searchReturnsOnCall map[int]struct {
		result1 []itinery.Itinery
		result2 error
	}
	SortByPriceStub        func(*[]itinery.Itinery)
	sortByPriceMutex       sync.RWMutex
	sortByPriceArgsForCall []struct {
		arg1 *[]itinery.Itinery
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeProvider) Explore(arg1 context.Context, arg2 provider.Request, arg3 string) ([]itinery.ExploreItinery, error) {
	fake.exploreMutex.Lock()
	ret, specificReturn := fake.exploreReturnsOnCall[len(fake.exploreArgsForCall)]
	fake.exploreArgsForCall = append(fake.exploreArgsForCall, struct {
		arg1 context.Context
		arg2 provider.Request
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.ExploreStub
	fakeReturns := fake.exploreReturns
	fake.recordInvocation("Explore", []interface{}{arg1, arg2, arg3})
	fake.exploreMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeProvider) ExploreCallCount() int {
	fake.exploreMutex.RLock()
	defer fake.exploreMutex.RUnlock()
	return len(fake.exploreArgsForCall)
}

func (fake *FakeProvider) ExploreCalls(stub func(context.Context, provider.Request, string) ([]itinery.ExploreItinery, error)) {
	fake.exploreMutex.Lock()
	defer fake.exploreMutex.Unlock()
	fake.ExploreStub = stub
}

func (fake *FakeProvider) ExploreArgsForCall(i int) (context.Context, provider.Request, string) {
	fake.exploreMutex.RLock()
	defer fake.exploreMutex.RUnlock()
	argsForCall := fake.exploreArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeProvider) ExploreReturns(result1 []itinery.ExploreItinery, result2 error) {
	fake.exploreMutex.Lock()
	defer fake.exploreMutex.Unlock()
	fake.ExploreStub = nil
	fake.exploreReturns = struct {
		result1 []itinery.ExploreItinery
		result2 error
	}{result1, result2}
}

func (fake *FakeProvider) ExploreReturnsOnCall(i int, result1 []itinery.ExploreItinery, result2 error) {
	fake.exploreMutex.Lock()
	defer fake.exploreMutex.Unlock()
	fake.ExploreStub = nil
	if fake.exploreReturnsOnCall == nil {
		fake.exploreReturnsOnCall = make(map[int]struct {
			result1 []itinery.ExploreItinery
			result2 error
		})
	}
	fake.exploreReturnsOnCall[i] = struct {
		result1 []itinery.ExploreItinery
		result2 error
	}{result1, result2}
}

func (fake *FakeProvider) Search(arg1 context.Context, arg2 provider.Request) ([]itinery.Itinery, error) {
	fake.searchMutex.Lock()
	ret, specificReturn := fake.searchReturnsOnCall[len(fake.searchArgsForCall)]
	fake.searchArgsForCall = append(fake.searchArgsForCall, struct {
		arg1 context.Context
		arg2 provider.Request
	}{arg1, arg2})
	stub := fake.SearchStub
	fakeReturns := fake.searchReturns
	fake.recordInvocation("Search", []interface{}{arg1, arg2})
	fake.searchMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeProvider) SearchCallCount() int {
	fake.searchMutex.RLock()
	defer fake.searchMutex.RUnlock()
	return len(fake.searchArgsForCall)
}

func (fake *FakeProvider) SearchCalls(stub func(context.Context, provider.Request) ([]itinery.Itinery, error)) {
	fake.searchMutex.Lock()
	defer fake.searchMutex.Unlock()
	fake.SearchStub = stub
}

func (fake *FakeProvider) SearchArgsForCall(i int) (context.Context, provider.Request) {
	fake.searchMutex.RLock()
	defer fake.searchMutex.RUnlock()
	argsForCall := fake.searchArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeProvider) SearchReturns(result1 []itinery.Itinery, result2 error) {
	fake.searchMutex.Lock()
	defer fake.searchMutex.Unlock()
	fake.SearchStub = nil
	fake.searchReturns = struct {
		result1 []itinery.Itinery
		result2 error
	}{result1, result2}
}

func (fake *FakeProvider) SearchReturnsOnCall(i int, result1 []itinery.Itinery, result2 error) {
	fake.searchMutex.Lock()
	defer fake.searchMutex.Unlock()
	fake.SearchStub = nil
	if fake.searchReturnsOnCall == nil {
		fake.searchReturnsOnCall = make(map[int]struct {
			result1 []itinery.Itinery
			result2 error
		})
	}
	fake.searchReturnsOnCall[i] = struct {
		result1 []itinery.Itinery
		result2 error
	}{result1, result2}
}

func (fake *FakeProvider) SortByPrice(arg1 *[]itinery.Itinery) {
	fake.sortByPriceMutex.Lock()
	fake.sortByPriceArgsForCall = append(fake.sortByPriceArgsForCall, struct {
		arg1 *[]itinery.Itinery
	}{arg1})
	stub := fake.SortByPriceStub
	fake.recordInvocation("SortByPrice", []interface{}{arg1})
	fake.sortByPriceMutex.Unlock()
	if stub != nil {
		fake.SortByPriceStub(arg1)
	}
}

func (fake *FakeProvider) SortByPriceCallCount() int {
	fake.sortByPriceMutex.RLock()
	defer fake.sortByPriceMutex.RUnlock()
	return len(fake.sortByPriceArgsForCall)
}

func (fake *FakeProvider) SortByPriceCalls(stub func(*[]itinery.Itinery)) {
	fake.sortByPriceMutex.Lock()
	defer fake.sortByPriceMutex.Unlock()
	fake.SortByPriceStub = stub
}

func (fake *FakeProvider) SortByPriceArgsForCall(i int) *[]itinery.Itinery {
	fake.sortByPriceMutex.RLock()
	defer fake.sortByPriceMutex.RUnlock()
	argsForCall := fake.sortByPriceArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeProvider) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeProvider) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ provider.Provider = new(FakeProvider)
